name: "PostHog: Sourcemaps Inject & Upload"

description: "Inject and upload sourcemaps with posthog-cli"

author: "PostHog"

branding:
  icon: upload-cloud
  color: purple

inputs:
  directory:
    description: "Directory containing built assets (e.g., dist)"
    required: true
  host:
    description: "Optional PostHog host"
    required: false
  cli-token:
    description: "PostHog CLI token"
    required: true
  env-id:
    description: "PostHog environment ID"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install posthog CLI
      shell: bash
      run: npm i -g @posthog/cli

    - name: List directories
      shell: bash
      run: ls -a ./

    - name: Inject sourcemaps
      shell: bash
      env:
        POSTHOG_CLI_ENV_ID: ${{ inputs.env-id }}
        POSTHOG_CLI_TOKEN: ${{ inputs.cli-token }}
      run: posthog-cli sourcemap inject --directory "${{ inputs.directory }}"

    - name: Upload sourcemaps
      shell: bash
      env:
        POSTHOG_CLI_ENV_ID: ${{ inputs.env-id }}
        POSTHOG_CLI_TOKEN: ${{ inputs.cli-token }}
      run: posthog-cli sourcemap upload --directory "${{ inputs.directory }}"
