name: Build and Upload Sourcemaps

on:
  push:
    branches: [main]

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Inject & upload sourcemaps to PostHog
        uses: ./
        env:
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
        with:
          directory: dist
