name: Build and Upload Sourcemaps

on:
  push:
    branches: [main]

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build
        with:
          version: 8

      - name: Inject & upload sourcemaps to PostHog
        uses: ./
        env:
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
        with:
          directory: dist
